language: node_js
node_js:
  - "6.14.2"

branches:
    only:
      - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  cls

after_success:
  -firebase deploy --token $FIREBASE_TOKEN